//
// Generated file, do not edit! Created by nedtool 5.5 from Info.msg.
//

#ifndef __INFO_M_H
#define __INFO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Info.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Info
 * {
 *     int host_id;
 * }
 * </pre>
 */
class Info : public ::omnetpp::cPacket
{
  protected:
    int host_id;

  private:
    void copy(const Info& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Info&);

  public:
    Info(const char *name=nullptr, short kind=0);
    Info(const Info& other);
    virtual ~Info();
    Info& operator=(const Info& other);
    virtual Info *dup() const override {return new Info(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getHost_id() const;
    virtual void setHost_id(int host_id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Info& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Info& obj) {obj.parsimUnpack(b);}


#endif // ifndef __INFO_M_H

